collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

navigation_header:
- title: Home
  url: /
- title: Hobbies
  url: /elements/
- title: Blog
  url: /blog/
- title: Subjects
  url: /categories/
- title: Search
  url: /search/
  
navigation_footer:
- title: Created by Rachel Huls
  url: /about/
  
social_links: 
  #Twitter: https://twitter.com/usrname
  #LinkedIn: https://www.linkedin.com/in/usrname
  GitHub: https://github.com/rachelhuls
  #link: https://sitename.com
  #RSS: /feed.xml
  email: rh@hulsfamily.com
