title: Rachel Huls
description: This is my personal website.
url: https://rachelhuls.github.io/
author: Rachel Huls
email: rh@hulsfamily.com
profile_pic: meFenceSquare.PNG

collections:
  category:
    output: true
    permalink: /:categories/:title/
  tags:
    output: true
    permalink: /:tags/:title/
  posts: 
    output: true
    
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include:
  - _pages
    
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
    
    
defaults:
  - scope:
      path: ""
      type: posts
    values: 
      layout: "post"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      path: ""
      type: tags
    values:
      layout: "tags"
  - scope:
      path: ""
    values:
      layout: "default"

navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Categories
  url: /categories/
- title: Tags
  url: /tags/
- title: About
  url: /about/
  
navigation_footer:
- title: Created by Rachel Huls
  url: https://rachelhuls.github.io/
  
social_links: 
  #Twitter: https://twitter.com/usrname
  #LinkedIn: https://www.linkedin.com/in/usrname
  GitHub: https://github.com/rachelhuls
  #link: https://sitename.com
  #RSS: /feed.xml
  email: rh@hulsfamily.com
  

