title: Rachel Huls
description: This is my personal website.
url: https://rachelhuls.github.io/
author: Rachel Huls
email: rh@hulsfamily.com
profile_pic: meFenceSquare.PNG

collections:
  categories:
    output: true
  projects:
    output: true
  posts: 
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values: 
      layout: "post"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: About
  url: /about/
  
navigation_footer:
- title: Created by Rachel Huls
  url: https://rachelhuls.github.io/
  
social_links: 
  #Twitter: https://twitter.com/usrname
  #LinkedIn: https://www.linkedin.com/in/usrname
  GitHub: https://github.com/rachelhuls
  #link: https://sitename.com
  #RSS: /feed.xml
  email: rh@hulsfamily.com
