collections:
  posts:
    output: true
  notes:
    output: true
  hobbies:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
  - scope:
      path: ""
      type: "hobbies"
    values:
      layout: "hobby"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

navigation_header:
- title: Home
  url: /
- title: Notes
  url: /notes/
- title: Hobbies
  url: /hobbies/
- title: Blog
  url: /blog/
- title: Projects
  url: /projects/
- title: About
  url: /about/
  
navigation_footer:
- title: Created by Rachel Huls
  url: /about/
  
social_links: 
  #Twitter: https://twitter.com/usrname
  #LinkedIn: https://www.linkedin.com/in/usrname
  GitHub: https://github.com/rachelhuls
  #link: https://sitename.com
  #RSS: /feed.xml
  email: rh@hulsfamily.com
